language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

env:
  global:
    - secure: ideKv/fIToOKy6VRbLTFe2RsVAazKGVYgt/OCRZU7DcYzwwQHRsqhqfrNd+1LOGUb7PW07iEKtDLMB2h4aKrRjJt+4E48XFIPv2Wr2jcKJDlIO+pGQJg/P3Gjsmc3pCJjb5O7S0l2Bz+UpzYINO4foqBhNgmtaNrZCxh7AEhKu6JET/CJN3oD55WChInXX9E0E0jPyqHyhquaUqVYbP7SVksf5xzpyw9lg5BXOm1uHIyvfW4vQZsGsmGaNd4A2Qehhtgz01RZWb2WVq2nudvIW7CywtECsZIOoVIbRhqVMEBOaS8uCvw47porF13nu5EZrLJUbiR9g2cm5u4rjohoiCgdd/l++3Bqtu6H59QhLJb3UNL5mNWlPM1adhrDmTgu6L9XmgEVk1FG065V167QBhBJlZKMSVuApW5PG+CJ9s6UN9xEjLjpdpyh8mFst4mjXVRhH1p0nI2sZr8Y05dM3QL19NXVVDFZvn7ZC8eha9Ow2SqF3i9LuTdcAJ4sAhtvH48dKev5xN9XNippLTqaJiPsu73s7PupcrMj7e093+DBIfRK4N4IuO4Ue9KzYuu5RSbz33XMBrnww+6DJZN1ebtOx317TZ3bUBSr2syDC3abaxwNRfzJkVuxbPqjdy/us+tRMltN+ShEo5VpG0PIgKa/8KmLABtJ84U+Dem8cI=

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo package --verbose

deploy:
  provider: script
  script: cargo publish --verbose --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
