[package]
name = "git-appraise"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
git2 = "0.3"
iron = "0.2.6"
serde = "0.6.7"
serde_json = "0.6.0"
serde_macros = "0.6.0"
pulldown-cmark = "0.0.5"

[dependencies.maud]
git = "https://github.com/lfairy/maud"

[dependencies.maud_macros]
git = "https://github.com/lfairy/maud"

[dependencies.router]
git = "https://github.com/iron/router"

[dependencies.logger]
git = "https://github.com/iron/logger"
